package com.application1.Enums;

public enum ConfigEnum {
	URL,
	FBURL,
	OVERRIDEREPORTS,
	PASSEDSTEPSCREENSHOT,
	FAILEDSTEPSCREENSHOT,
	SKIPPEDSTEPSCREENSHOT,
	SENDREPORTTOELK,
	RETRYFAILEDTESTCASES
}
